### PR TITLE
Keepalive in basic auth

### PR DESCRIPTION
**Pull request by kei-s**
If specified `EXPRESS_USER` and `EXPRESS_PASSWORD`, it should post keepalive in that authentication.

https://hubot.github.com/docs/scripting/#http-listener

### CODE REVIEW

**Comment by treby** [comment]
@kei-s Thank you for sending pull request!
Looks good to me. One point, we would need some README changes for the environment variables.
What do you think? @technicalpickles

**Comment by technicalpickles** [comment]
Good find! Yeah, you would definitely need this if you are using basicauth.

> Looks good to me. One point, we would need some README changes for the environment variables. What do you think?

These environment variables are documented in hubot (https://hubot.github.com/docs/scripting/#http-listener), but it would be worth mentioning in the README that it takes these into account. If a user is using basicauth, they'd set those environment variables for hubot, so there wouldn't be any extra work to use it in  hubot-heroku-keepalive.

**Comment by treby** [comment]
I understood. Thank you for explaining!

**Comment by treby** [comment]
Now, do you have anything to concern about this?
If nothing, I'll merge it. /cc @technicalpickles

**Comment by technicalpickles** [comment]
@treby no concerns here

**Comment by treby** [comment]
merged. thanks @kei-s

**Comment by technicalpickles** [comment]
@treby did you do a release yet that includes this?

**Comment by treby** [comment]
@technicalpickles not yet. i wondered if i do release. and if i should, which is better minor or patch?

**Comment by technicalpickles** [comment]
@treby if it's not released, people won't be able to update their own hubots to use it. I'd consider this one a bug fix, since hubots with basic auth wouldn't work previously, so patch release.

**Comment by treby** [comment]
@technicalpickles Thank you for your notice and describing! I've done the patch release includes this.

**Pull request merged**
